version: "3.8"

services:
  app:
    image: teamflow
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test_db_2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Poorna@1210
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
#      - SPRING_SQL_INIT_MODE=always
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_CACHE_TYPE=redis
    platform: linux/amd64
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=test_db_2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Poorna@1210
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    platform: linux/amd64
  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    platform: linux/amd64
volumes:
  postgres-data: